
enum Permisos {
  PROPIETARIO_LECTURA,
  PROPIETARIO_ESCRITURA,
  PROPIETARIO_EJECUCION,
  GRUPO_LECTURA,
  GRUPO_ESCRITURA,
  GRUPO_EJECUCION,
  OTROS_LECTURA,
  OTROS_ESCRITURA,
  OTROS_EJECUCION
}